name: Java CI

on: 
   push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'adopt'
        # Step that does that actual cache save and restore
      - uses: actions/cache@v1
        with:
         path: ~/.m2/repository
         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
         restore-keys: |
          ${{ runner.os }}-maven-
     # Step that runs the tests
      - name: Maven Verify 
        run: mvn clean test 
      - name: generate report
        uses: actions/upload-artifact@v2
        with:
          name: report 
          path: reports/coverage
      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: report
          path: reports/coverage

      - name: Upload Test Report
        run:  bash <(curl -s https://codecov.io/bash) -f "reports/coverage/report.xml"
     
     
