name: Java CI

on: 
   push:
jobs:
 coverage:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - run: mvn -B verify --no-transfer-progress
    - uses: codecov/codecov-action@v1
      with:
        file: ./**/target/site/jacoco/jacoco.xml
        name: codecov
      
     
     
