name: Java CI

on: 
   push:
jobs:
 coverage:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
        
    - name: Build with Maven
      run: mvn -B verify

    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: >
          /target/jacoco-ut/jacoco.csv
      
     
     
