name: Unit Test - Java

on: [push, pull_request]
jobs:
 coverage:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11   
    - name: run Unit Test with Maven
      run: mvn --batch-mode --update-snapshots test
      
     
     
